### ISSUE TITLE
Hello Michael

### ISSUE THREAD

**Issue by szaghi** [MichaelSiehl/MPMD-with-Fortran-2008-Coarrays#1]
Welcome on GitHub, I hope you will like to join us https://github.com/orgs/Fortran-FOSS-Programmers

Anyhow... I will follow you :smile:

**Comment by MichaelSiehl** [comment]
Hi Stefano,
thanks for your encouragement. I intend to join your group shortly. Just need a couple of days to get a bit more familiar with GitHub, I guess ;-)

cheers
Michael

**Comment by szaghi** [comment]
@MichaelSiehl Keep all the time you need.

In the meanwhile, I will send you the invitation.

A great step for the GitHub Fortraners!
